version: "3.5"
services:
  api:
    build:
      context: .
      cache_from:
        - python:3.8-alpine
      args:
        ENVIRONMENT: ${ENVIRONMENT}
    image: visitor:latest
    volumes:
      - type: bind
        source: .
        target: /usr/src/app
    depends_on:
      - db
      - broker
    ports:
      - "8000:8000"
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: visitor
      POSTGRES_USER: visitor
      POSTGRES_PASSWORD: v1s170r
    ports:
      - "5432:5432"
  broker:
    image: rabbitmq
    restart: on-failure
    ports:
      - "5672:5672"
